# Generated by Django 5.0.4 on 2024-04-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('animal_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('adopted', models.BooleanField(default=False)),
                ('medical_history', models.TextField()),
                ('treatment_history', models.TextField()),
                ('treatment_in_progress', models.BooleanField(default=False)),
                ('treatment_costs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('picture', models.ImageField(blank=True, default='default.png', null=True, upload_to='pets/')),
                ('deceased', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
