# Generated by Django 5.0.4 on 2024-04-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pet_adoption_history_alter_pet_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='medical_history',
            field=models.TextField(default='No Medical History'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='treatment_history',
            field=models.TextField(default='No Treatment History'),
        ),
    ]
