# Generated by Django 5.0.4 on 2024-04-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_pet_medical_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='up_for_adoption',
            field=models.BooleanField(default=False),
        ),
    ]
