# Generated by Django 5.0.4 on 2024-04-27 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_pet_up_for_adoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='treatment_costs',
        ),
        migrations.AddField(
            model_name='pet',
            name='total_treatment_costs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('medical_attention', models.TextField()),
                ('vet', models.CharField(max_length=200)),
                ('treatment_cost', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pet')),
            ],
        ),
    ]
